"""Utility modules for the tox-older project."""

from .intoxicacao_analysis import (
    DEFAULT_END_YEAR,
    DEFAULT_SEX_PALETTE,
    DEFAULT_START_YEAR,
    build_dashboard_payload,
    build_descriptive_stats,
    build_insight_lines,
    build_overall_by_year,
    build_state_case_totals,
    build_state_summary,
    build_state_year,
    build_top_groups_by_state,
    build_toxic_profile,
    build_year_totals,
    copy_plotly_bundle,
    filter_year_window,
    format_insights_markdown,
    load_intoxicacao_tidy,
    save_overall_analysis_charts,
    save_state_share_pie_charts,
    save_state_sex_timeseries_charts,
    save_top_toxic_chart,
    summarize_year_coverage,
    write_json_report,
    write_text_report,
)

__all__ = [
    "DEFAULT_END_YEAR",
    "DEFAULT_SEX_PALETTE",
    "DEFAULT_START_YEAR",
    "build_dashboard_payload",
    "build_descriptive_stats",
    "build_insight_lines",
    "build_overall_by_year",
    "build_state_case_totals",
    "build_state_summary",
    "build_state_year",
    "build_top_groups_by_state",
    "build_toxic_profile",
    "build_year_totals",
    "copy_plotly_bundle",
    "filter_year_window",
    "format_insights_markdown",
    "load_intoxicacao_tidy",
    "save_overall_analysis_charts",
    "save_state_share_pie_charts",
    "save_state_sex_timeseries_charts",
    "save_top_toxic_chart",
    "summarize_year_coverage",
    "write_json_report",
    "write_text_report",
]
